# Generated by Django 5.1.6 on 2025-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='cooking_time_avg',
            field=models.IntegerField(default=0, verbose_name='Среднее время приготовления'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения'),
        ),
        migrations.AddField(
            model_name='category',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='Количество рецептов'),
        ),
    ]
